// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code. Version 3.4.1.854 Microsoft Reciprocal License (Ms-RL) 
//    <NameSpace>r1.elm_modelInfo.hl7.org</NameSpace><Collection>List</Collection><codeType>CSharp</codeType><EnableDataBinding>False</EnableDataBinding><EnableLazyLoading>False</EnableLazyLoading><TrackingChangesEnable>False</TrackingChangesEnable><GenTrackingClasses>False</GenTrackingClasses><HidePrivateFieldInIDE>False</HidePrivateFieldInIDE><EnableSummaryComment>False</EnableSummaryComment><VirtualProp>False</VirtualProp><IncludeSerializeMethod>False</IncludeSerializeMethod><UseBaseClass>False</UseBaseClass><GenBaseClass>False</GenBaseClass><GenerateCloneMethod>False</GenerateCloneMethod><GenerateDataContracts>False</GenerateDataContracts><CodeBaseTag>Net20</CodeBaseTag><SerializeMethodName>Serialize</SerializeMethodName><DeserializeMethodName>Deserialize</DeserializeMethodName><SaveToFileMethodName>SaveToFile</SaveToFileMethodName><LoadFromFileMethodName>LoadFromFile</LoadFromFileMethodName><GenerateXMLAttributes>False</GenerateXMLAttributes><OrderXMLAttrib>False</OrderXMLAttrib><EnableEncoding>False</EnableEncoding><AutomaticProperties>False</AutomaticProperties><GenerateShouldSerialize>False</GenerateShouldSerialize><DisableDebug>False</DisableDebug><PropNameSpecified>Default</PropNameSpecified><Encoder>UTF8</Encoder><CustomUsings></CustomUsings><ExcludeIncludedTypes>False</ExcludeIncludedTypes><EnableInitializeFields>True</EnableInitializeFields>
//  </auto-generated>
// ------------------------------------------------------------------------------
namespace r1.elm_modelInfo.hl7.org
{
    using System;
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System.Collections;
    using System.Xml.Schema;
    using System.ComponentModel;
    using System.Collections.Generic;


    public partial class ModelInfo
    {

        private List<ModelSpecifier> requiredModelInfoField;

        private List<TypeInfo> typeInfoField;

        private List<ConversionInfo> conversionInfoField;

        private List<ContextInfo> contextInfoField;

        private string nameField;

        private string versionField;

        private string urlField;

        private string targetUrlField;

        private string targetVersionField;

        private string schemaLocationField;

        private string targetQualifierField;

        private string patientClassNameField;

        private string patientClassIdentifierField;

        private string patientBirthDatePropertyNameField;

        private bool caseSensitiveField;

        private bool caseSensitiveFieldSpecified;

        private bool strictRetrieveTypingField;

        private bool strictRetrieveTypingFieldSpecified;

        private string defaultContextField;

        public ModelInfo()
        {
            this.contextInfoField = new List<ContextInfo>();
            this.conversionInfoField = new List<ConversionInfo>();
            this.typeInfoField = new List<TypeInfo>();
            this.requiredModelInfoField = new List<ModelSpecifier>();
        }

        public List<ModelSpecifier> requiredModelInfo
        {
            get
            {
                return this.requiredModelInfoField;
            }
            set
            {
                this.requiredModelInfoField = value;
            }
        }

        public List<TypeInfo> typeInfo
        {
            get
            {
                return this.typeInfoField;
            }
            set
            {
                this.typeInfoField = value;
            }
        }

        public List<ConversionInfo> conversionInfo
        {
            get
            {
                return this.conversionInfoField;
            }
            set
            {
                this.conversionInfoField = value;
            }
        }

        public List<ContextInfo> contextInfo
        {
            get
            {
                return this.contextInfoField;
            }
            set
            {
                this.contextInfoField = value;
            }
        }

        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        public string version
        {
            get
            {
                return this.versionField;
            }
            set
            {
                this.versionField = value;
            }
        }

        public string url
        {
            get
            {
                return this.urlField;
            }
            set
            {
                this.urlField = value;
            }
        }

        public string targetUrl
        {
            get
            {
                return this.targetUrlField;
            }
            set
            {
                this.targetUrlField = value;
            }
        }

        public string targetVersion
        {
            get
            {
                return this.targetVersionField;
            }
            set
            {
                this.targetVersionField = value;
            }
        }

        public string schemaLocation
        {
            get
            {
                return this.schemaLocationField;
            }
            set
            {
                this.schemaLocationField = value;
            }
        }

        public string targetQualifier
        {
            get
            {
                return this.targetQualifierField;
            }
            set
            {
                this.targetQualifierField = value;
            }
        }

        public string patientClassName
        {
            get
            {
                return this.patientClassNameField;
            }
            set
            {
                this.patientClassNameField = value;
            }
        }

        public string patientClassIdentifier
        {
            get
            {
                return this.patientClassIdentifierField;
            }
            set
            {
                this.patientClassIdentifierField = value;
            }
        }

        public string patientBirthDatePropertyName
        {
            get
            {
                return this.patientBirthDatePropertyNameField;
            }
            set
            {
                this.patientBirthDatePropertyNameField = value;
            }
        }

        public bool caseSensitive
        {
            get
            {
                return this.caseSensitiveField;
            }
            set
            {
                this.caseSensitiveField = value;
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool caseSensitiveSpecified
        {
            get
            {
                return this.caseSensitiveFieldSpecified;
            }
            set
            {
                this.caseSensitiveFieldSpecified = value;
            }
        }

        public bool strictRetrieveTyping
        {
            get
            {
                return this.strictRetrieveTypingField;
            }
            set
            {
                this.strictRetrieveTypingField = value;
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool strictRetrieveTypingSpecified
        {
            get
            {
                return this.strictRetrieveTypingFieldSpecified;
            }
            set
            {
                this.strictRetrieveTypingFieldSpecified = value;
            }
        }

        public string defaultContext
        {
            get
            {
                return this.defaultContextField;
            }
            set
            {
                this.defaultContextField = value;
            }
        }
    }

    public partial class ModelSpecifier
    {

        private string urlField;

        private string nameField;

        private string versionField;

        public string url
        {
            get
            {
                return this.urlField;
            }
            set
            {
                this.urlField = value;
            }
        }

        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        public string version
        {
            get
            {
                return this.versionField;
            }
            set
            {
                this.versionField = value;
            }
        }
    }

    public partial class ContextInfo
    {

        private NamedTypeSpecifier contextTypeField;

        private string nameField;

        private string keyElementField;

        private string birthDateElementField;

        public ContextInfo()
        {
            this.contextTypeField = new NamedTypeSpecifier();
        }

        public NamedTypeSpecifier contextType
        {
            get
            {
                return this.contextTypeField;
            }
            set
            {
                this.contextTypeField = value;
            }
        }

        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        public string keyElement
        {
            get
            {
                return this.keyElementField;
            }
            set
            {
                this.keyElementField = value;
            }
        }

        public string birthDateElement
        {
            get
            {
                return this.birthDateElementField;
            }
            set
            {
                this.birthDateElementField = value;
            }
        }
    }

    public partial class NamedTypeSpecifier : TypeSpecifier
    {

        private string modelNameField;

        private string namespaceField;

        private string nameField;

        public string modelName
        {
            get
            {
                return this.modelNameField;
            }
            set
            {
                this.modelNameField = value;
            }
        }

        public string @namespace
        {
            get
            {
                return this.namespaceField;
            }
            set
            {
                this.namespaceField = value;
            }
        }

        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
    }

    [System.Xml.Serialization.XmlIncludeAttribute(typeof(TupleTypeSpecifier))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(BoundParameterTypeSpecifier))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ParameterTypeSpecifier))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ChoiceTypeSpecifier))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(IntervalTypeSpecifier))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ListTypeSpecifier))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(NamedTypeSpecifier))]
    public abstract partial class TypeSpecifier
    {
    }

    public partial class TupleTypeSpecifier : TypeSpecifier
    {

        private List<TupleTypeSpecifierElement> elementField;

        public TupleTypeSpecifier()
        {
            this.elementField = new List<TupleTypeSpecifierElement>();
        }

        public List<TupleTypeSpecifierElement> element
        {
            get
            {
                return this.elementField;
            }
            set
            {
                this.elementField = value;
            }
        }
    }

    public partial class TupleTypeSpecifierElement
    {

        private TypeSpecifier elementTypeField;

        private string nameField;

        public TypeSpecifier elementType
        {
            get
            {
                return this.elementTypeField;
            }
            set
            {
                this.elementTypeField = value;
            }
        }

        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
    }

    public partial class BoundParameterTypeSpecifier : TypeSpecifier
    {

        private TypeSpecifier elementTypeSpecifierField;

        private string parameterNameField;

        private string boundTypeField;

        public TypeSpecifier elementTypeSpecifier
        {
            get
            {
                return this.elementTypeSpecifierField;
            }
            set
            {
                this.elementTypeSpecifierField = value;
            }
        }

        public string parameterName
        {
            get
            {
                return this.parameterNameField;
            }
            set
            {
                this.parameterNameField = value;
            }
        }

        public string boundType
        {
            get
            {
                return this.boundTypeField;
            }
            set
            {
                this.boundTypeField = value;
            }
        }
    }

    public partial class ParameterTypeSpecifier : TypeSpecifier
    {

        private string parameterNameField;

        public string parameterName
        {
            get
            {
                return this.parameterNameField;
            }
            set
            {
                this.parameterNameField = value;
            }
        }
    }

    public partial class ChoiceTypeSpecifier : TypeSpecifier
    {

        private List<TypeSpecifier> choiceField;

        public ChoiceTypeSpecifier()
        {
            this.choiceField = new List<TypeSpecifier>();
        }

        public List<TypeSpecifier> choice
        {
            get
            {
                return this.choiceField;
            }
            set
            {
                this.choiceField = value;
            }
        }
    }

    public partial class IntervalTypeSpecifier : TypeSpecifier
    {

        private TypeSpecifier pointTypeSpecifierField;

        private string pointTypeField;

        public TypeSpecifier pointTypeSpecifier
        {
            get
            {
                return this.pointTypeSpecifierField;
            }
            set
            {
                this.pointTypeSpecifierField = value;
            }
        }

        public string pointType
        {
            get
            {
                return this.pointTypeField;
            }
            set
            {
                this.pointTypeField = value;
            }
        }
    }

    public partial class ListTypeSpecifier : TypeSpecifier
    {

        private TypeSpecifier elementTypeSpecifierField;

        private string elementTypeField;

        public TypeSpecifier elementTypeSpecifier
        {
            get
            {
                return this.elementTypeSpecifierField;
            }
            set
            {
                this.elementTypeSpecifierField = value;
            }
        }

        public string elementType
        {
            get
            {
                return this.elementTypeField;
            }
            set
            {
                this.elementTypeField = value;
            }
        }
    }

    public partial class ConversionInfo
    {

        private TypeSpecifier fromTypeSpecifierField;

        private TypeSpecifier toTypeSpecifierField;

        private string functionNameField;

        private string fromTypeField;

        private string toTypeField;

        public TypeSpecifier fromTypeSpecifier
        {
            get
            {
                return this.fromTypeSpecifierField;
            }
            set
            {
                this.fromTypeSpecifierField = value;
            }
        }

        public TypeSpecifier toTypeSpecifier
        {
            get
            {
                return this.toTypeSpecifierField;
            }
            set
            {
                this.toTypeSpecifierField = value;
            }
        }

        public string functionName
        {
            get
            {
                return this.functionNameField;
            }
            set
            {
                this.functionNameField = value;
            }
        }

        public string fromType
        {
            get
            {
                return this.fromTypeField;
            }
            set
            {
                this.fromTypeField = value;
            }
        }

        public string toType
        {
            get
            {
                return this.toTypeField;
            }
            set
            {
                this.toTypeField = value;
            }
        }
    }

    public partial class TupleTypeInfoElement
    {

        private TypeSpecifier typeSpecifierField;

        private TypeSpecifier elementTypeSpecifierField;

        private string nameField;

        private string typeField;

        private string elementTypeField;

        private bool prohibitedField;

        private bool prohibitedFieldSpecified;

        private bool oneBasedField;

        private bool oneBasedFieldSpecified;

        public TypeSpecifier typeSpecifier
        {
            get
            {
                return this.typeSpecifierField;
            }
            set
            {
                this.typeSpecifierField = value;
            }
        }

        public TypeSpecifier elementTypeSpecifier
        {
            get
            {
                return this.elementTypeSpecifierField;
            }
            set
            {
                this.elementTypeSpecifierField = value;
            }
        }

        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        public string type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }

        public string elementType
        {
            get
            {
                return this.elementTypeField;
            }
            set
            {
                this.elementTypeField = value;
            }
        }

        public bool prohibited
        {
            get
            {
                return this.prohibitedField;
            }
            set
            {
                this.prohibitedField = value;
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool prohibitedSpecified
        {
            get
            {
                return this.prohibitedFieldSpecified;
            }
            set
            {
                this.prohibitedFieldSpecified = value;
            }
        }

        public bool oneBased
        {
            get
            {
                return this.oneBasedField;
            }
            set
            {
                this.oneBasedField = value;
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool oneBasedSpecified
        {
            get
            {
                return this.oneBasedFieldSpecified;
            }
            set
            {
                this.oneBasedFieldSpecified = value;
            }
        }
    }

    public partial class SearchInfo
    {

        private TypeSpecifier typeSpecifierField;

        private string nameField;

        private string pathField;

        private string typeField;

        private string labelField;

        private string descriptionField;

        private string definitionField;

        private string commentField;

        public TypeSpecifier typeSpecifier
        {
            get
            {
                return this.typeSpecifierField;
            }
            set
            {
                this.typeSpecifierField = value;
            }
        }

        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        public string path
        {
            get
            {
                return this.pathField;
            }
            set
            {
                this.pathField = value;
            }
        }

        public string type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }

        public string label
        {
            get
            {
                return this.labelField;
            }
            set
            {
                this.labelField = value;
            }
        }

        public string description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }

        public string definition
        {
            get
            {
                return this.definitionField;
            }
            set
            {
                this.definitionField = value;
            }
        }

        public string comment
        {
            get
            {
                return this.commentField;
            }
            set
            {
                this.commentField = value;
            }
        }
    }

    public partial class RelationshipInfo
    {

        private string contextField;

        private string relatedKeyElementField;

        public string context
        {
            get
            {
                return this.contextField;
            }
            set
            {
                this.contextField = value;
            }
        }

        public string relatedKeyElement
        {
            get
            {
                return this.relatedKeyElementField;
            }
            set
            {
                this.relatedKeyElementField = value;
            }
        }
    }

    public partial class ExpressionInfo
    {

        private string languageField;

        private string expressionField;

        public string language
        {
            get
            {
                return this.languageField;
            }
            set
            {
                this.languageField = value;
            }
        }

        public string expression
        {
            get
            {
                return this.expressionField;
            }
            set
            {
                this.expressionField = value;
            }
        }
    }

    public partial class ConstraintInfo
    {

        private List<ExpressionInfo> expressionField;

        private string nameField;

        private string severityField;

        private string descriptionField;

        private string messageField;

        public ConstraintInfo()
        {
            this.expressionField = new List<ExpressionInfo>();
        }

        public List<ExpressionInfo> expression
        {
            get
            {
                return this.expressionField;
            }
            set
            {
                this.expressionField = value;
            }
        }

        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        public string severity
        {
            get
            {
                return this.severityField;
            }
            set
            {
                this.severityField = value;
            }
        }

        public string description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }

        public string message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
            }
        }
    }

    public partial class BindingInfo
    {

        private string nameField;

        private string descriptionField;

        private BindingStrength strengthField;

        private string valueSetField;

        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        public string description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }

        public BindingStrength strength
        {
            get
            {
                return this.strengthField;
            }
            set
            {
                this.strengthField = value;
            }
        }

        public string valueSet
        {
            get
            {
                return this.valueSetField;
            }
            set
            {
                this.valueSetField = value;
            }
        }
    }

    public enum BindingStrength
    {

        /// <remarks/>
        Required,

        /// <remarks/>
        Extensible,

        /// <remarks/>
        Preferred,

        /// <remarks/>
        Example,
    }

    public partial class ClassInfoElement
    {

        private TypeSpecifier typeSpecifierField;

        private TypeSpecifier elementTypeSpecifierField;

        private BindingInfo bindingField;

        private List<ConstraintInfo> constraintField;

        private string nameField;

        private string typeField;

        private string elementTypeField;

        private bool prohibitedField;

        private bool prohibitedFieldSpecified;

        private bool oneBasedField;

        private bool oneBasedFieldSpecified;

        private string targetField;

        private string labelField;

        private string descriptionField;

        private string definitionField;

        private string commentField;

        private int minField;

        private bool minFieldSpecified;

        private string maxField;

        private bool mustSupportField;

        private bool mustSupportFieldSpecified;

        public ClassInfoElement()
        {
            this.constraintField = new List<ConstraintInfo>();
            this.bindingField = new BindingInfo();
        }

        public TypeSpecifier typeSpecifier
        {
            get
            {
                return this.typeSpecifierField;
            }
            set
            {
                this.typeSpecifierField = value;
            }
        }

        public TypeSpecifier elementTypeSpecifier
        {
            get
            {
                return this.elementTypeSpecifierField;
            }
            set
            {
                this.elementTypeSpecifierField = value;
            }
        }

        public BindingInfo binding
        {
            get
            {
                return this.bindingField;
            }
            set
            {
                this.bindingField = value;
            }
        }

        public List<ConstraintInfo> constraint
        {
            get
            {
                return this.constraintField;
            }
            set
            {
                this.constraintField = value;
            }
        }

        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        public string type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }

        public string elementType
        {
            get
            {
                return this.elementTypeField;
            }
            set
            {
                this.elementTypeField = value;
            }
        }

        public bool prohibited
        {
            get
            {
                return this.prohibitedField;
            }
            set
            {
                this.prohibitedField = value;
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool prohibitedSpecified
        {
            get
            {
                return this.prohibitedFieldSpecified;
            }
            set
            {
                this.prohibitedFieldSpecified = value;
            }
        }

        public bool oneBased
        {
            get
            {
                return this.oneBasedField;
            }
            set
            {
                this.oneBasedField = value;
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool oneBasedSpecified
        {
            get
            {
                return this.oneBasedFieldSpecified;
            }
            set
            {
                this.oneBasedFieldSpecified = value;
            }
        }

        public string target
        {
            get
            {
                return this.targetField;
            }
            set
            {
                this.targetField = value;
            }
        }

        public string label
        {
            get
            {
                return this.labelField;
            }
            set
            {
                this.labelField = value;
            }
        }

        public string description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }

        public string definition
        {
            get
            {
                return this.definitionField;
            }
            set
            {
                this.definitionField = value;
            }
        }

        public string comment
        {
            get
            {
                return this.commentField;
            }
            set
            {
                this.commentField = value;
            }
        }

        public int min
        {
            get
            {
                return this.minField;
            }
            set
            {
                this.minField = value;
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool minSpecified
        {
            get
            {
                return this.minFieldSpecified;
            }
            set
            {
                this.minFieldSpecified = value;
            }
        }

        public string max
        {
            get
            {
                return this.maxField;
            }
            set
            {
                this.maxField = value;
            }
        }

        public bool mustSupport
        {
            get
            {
                return this.mustSupportField;
            }
            set
            {
                this.mustSupportField = value;
            }
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool mustSupportSpecified
        {
            get
            {
                return this.mustSupportFieldSpecified;
            }
            set
            {
                this.mustSupportFieldSpecified = value;
            }
        }
    }

    public partial class TypeParameterInfo
    {

        private TypeSpecifier typeSpecifierField;

        private string nameField;

        private string constraintField;

        private string constraintTypeField;

        public TypeSpecifier typeSpecifier
        {
            get
            {
                return this.typeSpecifierField;
            }
            set
            {
                this.typeSpecifierField = value;
            }
        }

        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        public string constraint
        {
            get
            {
                return this.constraintField;
            }
            set
            {
                this.constraintField = value;
            }
        }

        public string constraintType
        {
            get
            {
                return this.constraintTypeField;
            }
            set
            {
                this.constraintTypeField = value;
            }
        }
    }

    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ChoiceTypeInfo))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(TupleTypeInfo))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ListTypeInfo))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(IntervalTypeInfo))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SimpleTypeInfo))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ClassInfo))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ProfileInfo))]
    public abstract partial class TypeInfo
    {

        private TypeSpecifier baseTypeSpecifierField;

        private string baseTypeField;

        public TypeSpecifier baseTypeSpecifier
        {
            get
            {
                return this.baseTypeSpecifierField;
            }
            set
            {
                this.baseTypeSpecifierField = value;
            }
        }

        public string baseType
        {
            get
            {
                return this.baseTypeField;
            }
            set
            {
                this.baseTypeField = value;
            }
        }
    }

    public partial class ChoiceTypeInfo : TypeInfo
    {

        private List<TypeSpecifier> typeField;

        private List<TypeSpecifier> choiceField;

        public ChoiceTypeInfo()
        {
            this.choiceField = new List<TypeSpecifier>();
            this.typeField = new List<TypeSpecifier>();
        }

        public List<TypeSpecifier> type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }

        public List<TypeSpecifier> choice
        {
            get
            {
                return this.choiceField;
            }
            set
            {
                this.choiceField = value;
            }
        }
    }

    public partial class TupleTypeInfo : TypeInfo
    {

        private List<TupleTypeInfoElement> elementField;

        public TupleTypeInfo()
        {
            this.elementField = new List<TupleTypeInfoElement>();
        }

        public List<TupleTypeInfoElement> element
        {
            get
            {
                return this.elementField;
            }
            set
            {
                this.elementField = value;
            }
        }
    }

    public partial class ListTypeInfo : TypeInfo
    {

        private TypeSpecifier elementTypeSpecifierField;

        private string elementTypeField;

        public TypeSpecifier elementTypeSpecifier
        {
            get
            {
                return this.elementTypeSpecifierField;
            }
            set
            {
                this.elementTypeSpecifierField = value;
            }
        }

        public string elementType
        {
            get
            {
                return this.elementTypeField;
            }
            set
            {
                this.elementTypeField = value;
            }
        }
    }

    public partial class IntervalTypeInfo : TypeInfo
    {

        private TypeSpecifier pointTypeSpecifierField;

        private string pointTypeField;

        public TypeSpecifier pointTypeSpecifier
        {
            get
            {
                return this.pointTypeSpecifierField;
            }
            set
            {
                this.pointTypeSpecifierField = value;
            }
        }

        public string pointType
        {
            get
            {
                return this.pointTypeField;
            }
            set
            {
                this.pointTypeField = value;
            }
        }
    }

    public partial class SimpleTypeInfo : TypeInfo
    {

        private string namespaceField;

        private string nameField;

        private string targetField;

        public string @namespace
        {
            get
            {
                return this.namespaceField;
            }
            set
            {
                this.namespaceField = value;
            }
        }

        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        public string target
        {
            get
            {
                return this.targetField;
            }
            set
            {
                this.targetField = value;
            }
        }
    }

    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ProfileInfo))]
    public partial class ClassInfo : TypeInfo
    {

        private List<TypeParameterInfo> parameterField;

        private List<ClassInfoElement> elementField;

        private List<RelationshipInfo> contextRelationshipField;

        private List<RelationshipInfo> targetContextRelationshipField;

        private List<SearchInfo> searchField;

        private List<ExpressionInfo> inferenceExpressionField;

        private List<ConstraintInfo> constraintField;

        private string namespaceField;

        private string nameField;

        private string identifierField;

        private string labelField;

        private string descriptionField;

        private string definitionField;

        private string commentField;

        private string targetField;

        private bool retrievableField;

        private string primaryCodePathField;

        private string primaryValueSetPathField;

        public ClassInfo()
        {
            this.constraintField = new List<ConstraintInfo>();
            this.inferenceExpressionField = new List<ExpressionInfo>();
            this.searchField = new List<SearchInfo>();
            this.targetContextRelationshipField = new List<RelationshipInfo>();
            this.contextRelationshipField = new List<RelationshipInfo>();
            this.elementField = new List<ClassInfoElement>();
            this.parameterField = new List<TypeParameterInfo>();
            this.retrievableField = false;
        }

        public List<TypeParameterInfo> parameter
        {
            get
            {
                return this.parameterField;
            }
            set
            {
                this.parameterField = value;
            }
        }

        public List<ClassInfoElement> element
        {
            get
            {
                return this.elementField;
            }
            set
            {
                this.elementField = value;
            }
        }

        public List<RelationshipInfo> contextRelationship
        {
            get
            {
                return this.contextRelationshipField;
            }
            set
            {
                this.contextRelationshipField = value;
            }
        }

        public List<RelationshipInfo> targetContextRelationship
        {
            get
            {
                return this.targetContextRelationshipField;
            }
            set
            {
                this.targetContextRelationshipField = value;
            }
        }

        public List<SearchInfo> search
        {
            get
            {
                return this.searchField;
            }
            set
            {
                this.searchField = value;
            }
        }

        public List<ExpressionInfo> inferenceExpression
        {
            get
            {
                return this.inferenceExpressionField;
            }
            set
            {
                this.inferenceExpressionField = value;
            }
        }

        public List<ConstraintInfo> constraint
        {
            get
            {
                return this.constraintField;
            }
            set
            {
                this.constraintField = value;
            }
        }

        public string @namespace
        {
            get
            {
                return this.namespaceField;
            }
            set
            {
                this.namespaceField = value;
            }
        }

        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        public string identifier
        {
            get
            {
                return this.identifierField;
            }
            set
            {
                this.identifierField = value;
            }
        }

        public string label
        {
            get
            {
                return this.labelField;
            }
            set
            {
                this.labelField = value;
            }
        }

        public string description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }

        public string definition
        {
            get
            {
                return this.definitionField;
            }
            set
            {
                this.definitionField = value;
            }
        }

        public string comment
        {
            get
            {
                return this.commentField;
            }
            set
            {
                this.commentField = value;
            }
        }

        public string target
        {
            get
            {
                return this.targetField;
            }
            set
            {
                this.targetField = value;
            }
        }

        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool retrievable
        {
            get
            {
                return this.retrievableField;
            }
            set
            {
                this.retrievableField = value;
            }
        }

        public string primaryCodePath
        {
            get
            {
                return this.primaryCodePathField;
            }
            set
            {
                this.primaryCodePathField = value;
            }
        }

        public string primaryValueSetPath
        {
            get
            {
                return this.primaryValueSetPathField;
            }
            set
            {
                this.primaryValueSetPathField = value;
            }
        }
    }

    public partial class ProfileInfo : ClassInfo
    {
    }
}
